### ISSUE TITLE
Missing License, please supply a license

### ISSUE THREAD

**Issue by AugustoResende** [VazkiiMods/AutoRegLib#49]
```
[15Aug2020 22:53:11.894] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (.lib-AutoRegLib-1.6-43.jar)
[15Aug2020 22:53:11.895] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:68)
[15Aug2020 22:53:11.895] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo$$Lambda$253/332699949.get(Unknown Source)
[15Aug2020 22:53:11.895] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Optional.orElseThrow(Optional.java:290)
[15Aug2020 22:53:11.895] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:68)
[15Aug2020 22:53:11.896] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:62)
[15Aug2020 22:53:11.896] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFile$$Lambda$234/2074658615.build(Unknown Source)
[15Aug2020 22:53:11.896] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:46)
[15Aug2020 22:53:11.896] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFile.identifyMods(ModFile.java:114)
[15Aug2020 22:53:11.896] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:116)
[15Aug2020 22:53:11.897] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[15Aug2020 22:53:11.897] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[15Aug2020 22:53:11.897] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[15Aug2020 22:53:11.897] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[15Aug2020 22:53:11.897] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$182/1204481453.apply(Unknown Source)
[15Aug2020 22:53:11.898] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[15Aug2020 22:53:11.898] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
[15Aug2020 22:53:11.898] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[15Aug2020 22:53:11.898] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[15Aug2020 22:53:11.898] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[15Aug2020 22:53:11.899] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15Aug2020 22:53:11.899] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[15Aug2020 22:53:11.899] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[15Aug2020 22:53:11.899] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[15Aug2020 22:53:11.899] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[15Aug2020 22:53:11.899] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

```

**Comment by Moonflowey** [comment]
Had the same issue, the reason was that i was playing on the wrong minecraft version. I assumed some 1.16.1 would also work in 1.16.2 since most of them didn't update, but nope. So your problem is also probably caused by something similar.

**Comment by Sindarin27** [comment]
All mods from 1.16.2 onwards require a license file, and this is often the only change required for compatibility among 1.16.1 and 1.16.2. Once a license is added, the mod will probably work across all 1.16 versions.

**Comment by avidleeCurious** [comment]
Same issue here. Could only get the error message to appear if no mods that rely on RegLib were present.

**Comment by Vazkii** [comment]
This happens when you're trying to run a 1.16.1 mod on a later version. ARL
doesn't support later versions yet.

**Comment by augustresende** [comment]
Outdated
