### ISSUE TITLE
Autoreglib Encountered an error during the complete event phase

### ISSUE THREAD

**Issue by muddle6969** [VazkiiMods/AutoRegLib#75]
Can someone help me with this? I installed mgnesium mod and made change in toml file from 1.18 to 1.18.1 and now autoreglib is not loading. Kindly help me fix this.
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
-- MOD autoreglib --
Details:
	Mod File: AutoRegLib-1.7-52.jar
	Failure message: AutoRegLib (autoreglib) encountered an error during the complete event phase
		java.lang.NullPointerException: null
	Mod Version: 1.7-52
	Mod Issue URL: https://github.com/Vazkii/AutoRegLib
	Exception message: java.lang.NullPointerException
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {re:mixin}
	at net.minecraft.client.color.block.BlockColors.handler$zbd000$preRegisterColor(BlockColors.java:532) ~[client-1.18.1-20211210.034407-srg.jar%2367!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.color.block.BlockColors.m_92589_(BlockColors.java) ~[client-1.18.1-20211210.034407-srg.jar%2367!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at vazkii.arl.util.RegistryHelper.loadCompleteClient(RegistryHelper.java:134) ~[AutoRegLib-1.7-52.jar%2352!/:1.7-52] {re:classloading}
	at vazkii.arl.util.RegistryHelper.lambda$loadComplete$3(RegistryHelper.java:118) ~[AutoRegLib-1.7-52.jar%2352!/:1.7-52] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:125) ~[fmlcore-1.18.1-39.0.79.jar%2368!/:?] {}
	at net.minecraftforge.fml.DistExecutor.runWhenOn(DistExecutor.java:109) ~[fmlcore-1.18.1-39.0.79.jar%2368!/:?] {}
	at vazkii.arl.util.RegistryHelper.loadComplete(RegistryHelper.java:118) ~[AutoRegLib-1.7-52.jar%2352!/:1.7-52] {re:classloading}
	at vazkii.arl.AutoRegLib.loadComplete(AutoRegLib.java:29) ~[AutoRegLib-1.7-52.jar%2352!/:1.7-52] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.79.jar%2369!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.79.jar%2368!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 7442292288 bytes (7097 MiB) / 8355053568 bytes (7968 MiB) up to 23622320128 bytes (22528 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700 Eight-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1109
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38095.01
	Virtual memory used (MB): 16487.03
	Swap memory total (MB): 5376.00
	Swap memory used (MB): 18.95
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx22G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		clienttweaks-forge-1.18-7.0.0.jar                 |Client Tweaks                 |clienttweaks                  |7.0.0               |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.18.1-3.1.1.jar              |More Villagers                |morevillagers                 |3.1.1               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		forgeautofish-4.0.0-1.18.x.jar                    |AutoFish for Forge            |forgeautofish                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		magnesium-0.4.0-alpha6.jar                        |Magnesium                     |magnesium                     |0.4.0-alpha5        |DONE      |Manifest: NOSIGNATURE
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.79-universal.jar                |Forge                         |forge                         |39.0.79             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18-5.0.0.1.jar                   |Comforts                      |comforts                      |1.18-5.0.0.1        |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |ERROR     |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 8e82f5af-db30-4be5-966e-24026070e6b0
	FML: 39.0
	Forge: net.minecraftforge:39.0.79

**Comment by muddle6969** [comment]
[crash-2022-02-23_21.07.13-fml.txt](https://github.com/VazkiiMods/AutoRegLib/files/8125705/crash-2022-02-23_21.07.13-fml.txt)

**Comment by Kana1000** [comment]
I had the exact same problem, turns out I was using an outdated version of autoreglib, same as you, switching to the new version seems to have fixed it.
